# Generated by Django 2.2.1 on 2019-07-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_notifications', '0002_auto_20171003_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticequeuebatch',
            name='send_till',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
