# Generated by Django 2.2.1 on 2019-08-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_notifications', '0003_noticequeuebatch_send_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticequeuebatch',
            name='send_after',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
